# Generated by Django 5.0.14 on 2026-06-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('alborz', 'البرز'), ('ardabil', 'اردبیل'), ('isfahan', 'اصفهان'), ('ilam', 'ایلام'), ('azerbaijan_east', 'آذربایجان شرقی'), ('azerbaijan_west', 'آذربایجان غربی'), ('bushehr', 'بوشهر'), ('tehran', 'تهران'), ('chaharmahal', 'چهارمحال و بختیاری'), ('south_khorasan', 'خراسان جنوبی'), ('khorasan_razavi', 'خراسان رضوی'), ('north_khorasan', 'خراسان شمالی'), ('khuzestan', 'خوزستان'), ('zanjan', 'زنجان'), ('semnan', 'سمنان'), ('sistan', 'سیستان و بلوچستان'), ('fars', 'فارس'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('kurdistan', 'کردستان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('kohgiluyeh', 'کهگیلویه و بویراحمد'), ('golestan', 'گلستان'), ('Gilan', 'گیلان'), ('lorestan', 'لرستان'), ('mazandaran', 'مازندران'), ('markazi', 'مرکزی'), ('hormozgan', 'هرمزگان'), ('hamadan', 'همدان'), ('yazd', 'یزد')], max_length=50, verbose_name='استان'),
        ),
    ]
