# Generated by Django 5.1.4 on 2026-06-28 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='کلید نشست')),
                ('caller_name', models.CharField(blank=True, max_length=120, verbose_name='نام تماس\u200cگیرنده')),
                ('caller_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('active', 'در حال انجام'), ('completed', 'پایان\u200cیافته'), ('callback', 'درخواست تماس مجدد'), ('missed', 'بی\u200cپاسخ')], default='active', max_length=20, verbose_name='وضعیت')),
                ('ai_powered', models.BooleanField(default=False, verbose_name='پاسخ با هوش مصنوعی')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه')),
                ('staff_note', models.TextField(blank=True, verbose_name='یادداشت کارشناس')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز مشتری')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع تماس')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان تماس')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='مدت (ثانیه)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال پیگیری'), ('done', 'انجام شد'), ('canceled', 'لغو شد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('agent_note', models.TextField(blank=True, verbose_name='یادداشت کارشناس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='callcenter.call', verbose_name='تماس مرتبط')),
            ],
            options={
                'verbose_name': 'درخواست تماس مجدد',
                'verbose_name_plural': 'درخواست\u200cهای تماس مجدد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('caller', 'مشتری'), ('agent', 'دستیار')], max_length=10, verbose_name='گوینده')),
                ('text', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='callcenter.call', verbose_name='تماس')),
            ],
            options={
                'verbose_name': 'بخش گفتگو',
                'verbose_name_plural': 'متن گفتگوی تماس',
                'ordering': ['created_at'],
            },
        ),
    ]
