# Generated by Django 5.0.14 on 2026-06-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vehicles/brands/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'برند خودرو',
                'verbose_name_plural': 'برندهای خودرو',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclebrand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'مدل خودرو',
                'verbose_name_plural': 'مدل\u200cهای خودرو',
                'ordering': ['name'],
                'unique_together': {('brand', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='VehicleTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تیپ')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='از سال')),
                ('year_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='تا سال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='vehicles.vehiclemodel', verbose_name='مدل')),
            ],
            options={
                'verbose_name': 'تیپ خودرو',
                'verbose_name_plural': 'تیپ\u200cهای خودرو',
                'ordering': ['name'],
            },
        ),
    ]
