# Generated by Django 5.0.14 on 2026-06-21 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='زیر عنوان')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برندهای محصول',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='شماره قطعه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (ریال)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت حراج (ریال)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('badge', models.CharField(blank=True, choices=[('', 'بدون برچسب'), ('new', 'جدید'), ('sale', 'حراج'), ('original', 'اصلی'), ('hot', 'پرفروش')], max_length=20, verbose_name='برچسب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='وزن (کیلوگرم)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand', verbose_name='برند')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='دسته\u200cبندی')),
                ('compatible_vehicles', models.ManyToManyField(blank=True, related_name='compatible_products', to='vehicles.vehicletrim', verbose_name='خودروهای سازگار')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('is_main', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('products', models.ManyToManyField(blank=True, related_name='wishlisted_by', to='shop.product', verbose_name='محصولات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لیست علاقه\u200cمندی',
                'verbose_name_plural': 'لیست\u200cهای علاقه\u200cمندی',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن نقد')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقد و بررسی',
                'verbose_name_plural': 'نقد و بررسی\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
